kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test ./...
  - sh scripts/build.sh

- name: publish
  image: plugins/docker
  settings:
    repo: plugins/aws-cli
    auto_tag: true
    dockerfile: docker/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
type: vm
name: linux-arm64
platform:
  os: linux
  arch: arm64
pool:
  use: ubuntu_arm64

steps:
  - name: environment
    image: golang:1.19
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.19
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -v -ldflags "-X main.version=" -a -tags netgo -o release/linux/arm64/plugin .
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.linux.arm64
      repo: plugins/slack
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-arm64
depends_on:
  - default
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**
---
kind: pipeline
type: vm
name: linux-amd64
platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: environment
    image: golang:1.19
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.19
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -v -ldflags "-X main.version=" -a -tags netgo -o release/linux/amd64/plugin .
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      repo: plugins/slack
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-amd64
depends_on:
  - default
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**
---
kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: arm64
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      auto_tag: "true"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: docker/manifest.tmpl
      ignore_missing: true
depends_on:
  - linux-amd64
  - linux-arm64
trigger:
  ref:
    - refs/heads/master
    - refs/tags/**